#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
do
  if [[ "$remote_ref" =~ refs/heads/(main|master)$ ]]; then
    echo "Running cargo clippy"
    cargo clippy --all-targets --all-features -- -D warnings
  elif [[ "$remote_ref" =~ refs/heads/staging$ ]]; then
    echo "Running cargo clippy"
    cargo clippy --all-targets --all-features
  else
    echo "No cargo clippy checks"
    continue
  fi

  CLIPPY_EXIT_CODE=$?

  if [[ $CLIPPY_EXIT_CODE -ne 0 ]]; then
    echo "Running cargo clippy reported issues on branch $remote_ref"
    exit $CLIPPY_EXIT_CODE
  fi

  echo "Running cargo sqlx prepare"
  cargo sqlx prepare --check

  SLQX_EXIT_CODE=$?

  if [[ $SQLX_EXIT_CODE -ne 0 ]]; then
    echo "Running cargo sqlx prepare reported issues on branch $remote_ref"
    exit $SQLX_EXIT_CODE
  fi
done

exit 0
