services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    pull_policy: always
    ports:
      - '8000:8000'
    command:
      - start
      - --log=trace
      - --user=root
      - --pass=root
    volumes:
      - surreal:/data

  backend:
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - surrealdb

volumes:
  surreal:
